# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Research Paper
    local_business_type: 'University'
    org_name: 'KTH Royal Institute of Technology'
    description: 'Can Visuo-motor policies benefit from random exploration data? A case study on stacking'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: false
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Read the Paper"
      url: "https://arxiv.org/abs/2503.23571"
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: '© {year} KTH Royal Institute of Technology'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
